##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [10]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([2,2,3,4])
print(a+b)
print(a-b)
print(a//b)
print(a*b)

[12 22 33 44]
[ 8 18 27 36]
[ 5 10 10 10]
[ 20  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [12]:
a=np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr*5)

[[ 5 10 15]
 [20 25 30]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [18]:
arr = np.array([4,8,15,16,23,42])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

108
18.0
15.5
12.315302134607444
151.66666666666666


You can also do the axis based operations row-Wise and Colum-wise

In [19]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


In [20]:
print(np.sum(data[0]))

6


In [22]:
print(np.sum(data,axis = 1)) #rows summation

[ 6 15 24]


In [23]:
print(np.sum(data,axis =0))

[12 15 18]


In [24]:
print(np.mean(data,axis =0))

[4. 5. 6.]
