# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
arr = np.array(['1',2,3,4,5])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

Lets create a matrix using list

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [16]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones([5,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.full([5,3],4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [21]:
np.arange(2,7,1)

array([2, 3, 4, 5, 6])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5,5)

array([[0.63879332, 0.86978714, 0.41531329, 0.8838173 , 0.09294693],
       [0.825926  , 0.48564248, 0.72686173, 0.54716693, 0.20765798],
       [0.98284294, 0.83117671, 0.93272408, 0.19300715, 0.58958523],
       [0.48900851, 0.42110395, 0.48829469, 0.46456957, 0.02088123],
       [0.67770367, 0.65610245, 0.16695158, 0.58833853, 0.55956863]])

In [31]:
np.random.randint(1,100,5) # 5 random int from 1 to 100

array([24, 83,  6, 86,  1])

In [35]:
np.random.randint(1,100,[2,3]) # 2x3 mat of random int from 1  to 10

array([[54, 35, 58],
       [68,  5, 39]])

In [37]:
arr = np.random.randn(2,4)
arr

array([[-0.21428711,  0.22078951, -1.14752715,  0.12925817],
       [ 0.17838793,  1.36712195, -1.17029833,  0.07192688]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution